[tool.poetry]
name = "poetry-package"
version = "0.1.0"
description = "I need this file"
authors = ["Khadijo <khadijoa@hiof.no>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
pytest = "^7.4.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
